name: cp-tf-inspect CI and Release Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (for semantic-release)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM dependencies
        run: npm install

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'

      - name: Build Linux Binary
        run: GOOS=linux GOARCH=amd64 go build -o cp-tf-inspect .

      - name: Run Unit Tests
        run: go test ./cmd/...

      - name: Run Integration Tests
        run: |
          ./cp-tf-inspect list-module-source --dir ./test/fixtures/basic
          go test ./test/...

      # Optionally upload PR preview (see previous best-practice notes)
      - name: Create Pre-release for PR
        if: github.event_name == 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pr-${{ github.event.pull_request.number }}-${{ github.run_number }}-${{ github.run_attempt }}
          name: Preview for PR #${{ github.event.pull_request.number }}, Run #${{ github.run_number }}, Attempt #${{ github.run_attempt }}
          prerelease: true
          draft: false
          files: cp-tf-inspect
          target_commitish: ${{ github.event.pull_request.head.sha }}
          make_latest: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Only do semantic-release on develop
      - name: Release on develop using semantic-release
        if: github.ref == 'refs/heads/develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release